---
all:
  hosts:
    control-plane:
      ansible_host: 51.250.11.205
      ansible_user: ubuntu
    node-1:
      ansible_host: 89.169.138.220
      ansible_user: ubuntu
    node-2:
      ansible_host: 89.169.160.113
      ansible_user: ubuntu
    node-3:
      ansible_host: 51.250.36.217
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        control-plane:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
    etcd:
      hosts:
        control-plane:
    k8s_cluster:
      vars:
        supplementary_addresses_in_ssl_keys: [51.250.11.205]
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}